services:
  run_machine:
    container_name: no_gps_btw
    build: .
    runtime: nvidia
    volumes:
      - ./src:/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true # docker run -i
    tty: true        # docker run -t